name: Build Docker containers
on:
  push:
    branches:
      - maint
  pull_request:
    branches:
      - maint

env:
  REGISTRY: ghcr.io
  IMAGE_PREFIX: ${{ github.repository }}

jobs:
  build-client:
    name: Build and push client/ Docker container
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 0

      - name: Build szurubooru/client
        uses: ./.github/actions/build-container-image
        with:
          context: client
          registry-password: ${{ secrets.GITHUB_TOKEN }}
  
  build-server:
    name: Build and push server/ Docker container
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 0

      - name: Build szurubooru/server
        uses: ./.github/actions/build-container-image
        with:
          context: server
          registry-password: ${{ secrets.GITHUB_TOKEN }}
