name: Run unit tests
on:
  pull_request:
    branches: [ "maint" ]

jobs:
  test-server:
    name: Run pytest for server/
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@988b5a0280414f521da01fcc63a27aeeb4b104db # v3.6.1

      - name: Build Image
        uses: docker/build-push-action@5cd11c3a4ced054e52742c5fd54dca954e0edd85 # v6.7.0
        env:
          DOCKER_BUILD_CHECKS_ANNOTATIONS: false
          DOCKER_BUILD_SUMMARY: false
          DOCKER_BUILD_RECORD_UPLOAD: false
        with:
          context: server
          load: true
          target: testing
          tags: test_container
          cache-from: type=gha,scope=test
          cache-to: type=gha,mode=max,scope=test
  
      - name: Run unit tests
        run: >
          docker run --rm -t test_container
          --color=no
          --cov-report=term-missing:skip-covered
          --cov=szurubooru
          szurubooru/
