name: Run unit tests
on: [push, pull_request]
jobs:
  test-server:
    name: Run pytest for server/
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@988b5a0280414f521da01fcc63a27aeeb4b104db # v3.6.1

      - name: Expose GitHub Runtime
        uses: crazy-max/ghaction-github-runtime@b3a9207c0e1ef41f4cf215303c976869d0c2c1c4 # v3.0.0

      - name: Build test container
        run: >
          docker buildx build --load
          --cache-to type=gha,mode=max,ghtoken=${{ secrets.GITHUB_TOKEN }},scope=test
          --cache-from type=gha,scope=test
          --platform linux/amd64 --target testing
          -t test_container
          ./server

      - name: Run unit tests
        run: >
          docker run --rm -t test_container
          --color=no
          --cov-report=term-missing:skip-covered
          --cov=szurubooru
          szurubooru/
